export type CategoryKey =
  | "daggdjur"
  | "faglar"
  | "fiskar"
  | "svampar"
  | "trad"
  | "vaxter"

export type Species = {
  slug: string
  name: string
  latin: string
  badge: string
  category: CategoryKey
  image: string
}

export const categoryFilters: { key: CategoryKey | "alla"; label: string }[] = [
  { key: "alla", label: "Alla arter" },
  { key: "daggdjur", label: "Däggdjur" },
  { key: "faglar", label: "Fåglar" },
  { key: "fiskar", label: "Fiskar" },
  { key: "svampar", label: "Svampar" },
  { key: "trad", label: "Träd" },
  { key: "vaxter", label: "Växter & Bär" },
]

export const species: Species[] = [
  {
    slug: "lodjur",
    name: "Lodjur",
    latin: "Lynx lynx",
    badge: "Däggdjur",
    category: "daggdjur",
    image: "/images/sp-lynx.png",
  },
  {
    slug: "rodrav",
    name: "Rödräv",
    latin: "Vulpes vulpes",
    badge: "Däggdjur",
    category: "daggdjur",
    image: "/images/rodrav-hero.png",
  },
  {
    slug: "alg",
    name: "Älg",
    latin: "Alces alces",
    badge: "Däggdjur",
    category: "daggdjur",
    image: "/images/alg-hero.png",
  },
  {
    slug: "grasal",
    name: "Gråsäl",
    latin: "Halichoerus grypus",
    badge: "Däggdjur",
    category: "daggdjur",
    image: "/images/sp-seal.png",
  },
  {
    slug: "brunbjorn",
    name: "Brunbjörn",
    latin: "Ursus arctos",
    badge: "Däggdjur",
    category: "daggdjur",
    image: "/images/brunbjorn-hero.png",
  },
  {
    slug: "varg",
    name: "Varg",
    latin: "Canis lupus",
    badge: "Däggdjur",
    category: "daggdjur",
    image: "/images/varg-hero.png",
  },
  {
    slug: "jarv",
    name: "Järv",
    latin: "Gulo gulo",
    badge: "Däggdjur",
    category: "daggdjur",
    image: "/images/jarv-hero.png",
  },
  {
    slug: "gravling",
    name: "Grävling",
    latin: "Meles meles",
    badge: "Däggdjur",
    category: "daggdjur",
    image: "/images/gravling-hero.png",
  },
  {
    slug: "radjur",
    name: "Rådjur",
    latin: "Capreolus capreolus",
    badge: "Däggdjur",
    category: "daggdjur",
    image: "/images/radjur-hero.png",
  },
  {
    slug: "havsorn",
    name: "Havsörn",
    latin: "Haliaeetus albicilla",
    badge: "Fågel",
    category: "faglar",
    image: "/images/species-eagle.png",
  },
  {
    slug: "fiskgjuse",
    name: "Fiskgjuse",
    latin: "Pandion haliaetus",
    badge: "Fågel",
    category: "faglar",
    image: "/images/sp-osprey.png",
  },
  {
    slug: "spillkraka",
    name: "Spillkråka",
    latin: "Dryocopus martius",
    badge: "Fågel",
    category: "faglar",
    image: "/images/sp-woodpecker.png",
  },
  {
    slug: "bofink",
    name: "Bofink",
    latin: "Fringilla coelebs",
    badge: "Fågel",
    category: "faglar",
    image: "/images/faglar/bofink-hero.png",
  },
  {
    slug: "gratrut",
    name: "Gråtrut",
    latin: "Larus argentatus",
    badge: "Fågel",
    category: "faglar",
    image: "/images/faglar/gratrut-hero.png",
  },
  {
    slug: "tjader",
    name: "Tjäder",
    latin: "Tetrao urogallus",
    badge: "Fågel",
    category: "faglar",
    image: "/images/faglar/tjader-hero.png",
  },
  {
    slug: "graspett",
    name: "Gråspett",
    latin: "Picus canus",
    badge: "Fågel",
    category: "faglar",
    image: "/images/faglar/graspett-hero.png",
  },
  {
    slug: "orre",
    name: "Orre",
    latin: "Lyrurus tetrix",
    badge: "Fågel",
    category: "faglar",
    image: "/images/faglar/orre-hero.png",
  },
  {
    slug: "lappuggla",
    name: "Lappuggla",
    latin: "Strix nebulosa",
    badge: "Fågel",
    category: "faglar",
    image: "/images/faglar/lappuggla-hero.png",
  },
  {
    slug: "grahager",
    name: "Gråhäger",
    latin: "Ardea cinerea",
    badge: "Fågel",
    category: "faglar",
    image: "/images/faglar/grahager-hero.png",
  },
  {
    slug: "nattskarra",
    name: "Nattskärra",
    latin: "Caprimulgus europaeus",
    badge: "Fågel",
    category: "faglar",
    image: "/images/faglar/nattskarra-hero.png",
  },
  {
    slug: "koltrast",
    name: "Koltrast",
    latin: "Turdus merula",
    badge: "Fågel",
    category: "faglar",
    image: "/images/faglar/koltrast-hero.png",
  },
  {
    slug: "domherre",
    name: "Domherre",
    latin: "Pyrrhula pyrrhula",
    badge: "Fågel",
    category: "faglar",
    image: "/images/faglar/domherre-hero.png",
  },
  {
    slug: "notskrika",
    name: "Nötskrika",
    latin: "Garrulus glandarius",
    badge: "Fågel",
    category: "faglar",
    image: "/images/faglar/notskrika-hero.png",
  },
  {
    slug: "smalom",
    name: "Smålom",
    latin: "Gavia stellata",
    badge: "Fågel",
    category: "faglar",
    image: "/images/faglar/smalom-hero.png",
  },
  {
    slug: "stromming",
    name: "Strömming",
    latin: "Clupea harengus",
    badge: "Fisk",
    category: "fiskar",
    image: "/images/sp-herring.png",
  },
  {
    slug: "lax",
    name: "Lax",
    latin: "Salmo salar",
    badge: "Fisk",
    category: "fiskar",
    image: "/images/sp-salmon.png",
  },
  {
    slug: "gadda",
    name: "Gädda",
    latin: "Esox lucius",
    badge: "Fisk",
    category: "fiskar",
    image: "/images/fiskar/Gadda_Huvudbild_01.png",
  },
  {
    slug: "abborre",
    name: "Abborre",
    latin: "Perca fluviatilis",
    badge: "Fisk",
    category: "fiskar",
    image: "/images/fiskar/Abborre_Huvudbild_01.png",
  },
  {
    slug: "oring",
    name: "Öring",
    latin: "Salmo trutta",
    badge: "Fisk",
    category: "fiskar",
    image: "/images/fiskar/Oring_Huvudbild_01.png",
  },
  {
    slug: "sik",
    name: "Sik",
    latin: "Coregonus lavaretus",
    badge: "Fisk",
    category: "fiskar",
    image: "/images/fiskar/Sik_Huvudbild_01.png",
  },
  {
    slug: "al",
    name: "Ål",
    latin: "Anguilla anguilla",
    badge: "Fisk",
    category: "fiskar",
    image: "/images/fiskar/Al_Huvudbild_01.png",
  },
  {
    slug: "lin",
    name: "Lin",
    latin: "Linum usitatissimum",
    badge: "Växt",
    category: "vaxter",
    image: "/images/sp-flax.png",
  },
  {
    slug: "hjortron",
    name: "Hjortron",
    latin: "Rubus chamaemorus",
    badge: "Bär",
    category: "vaxter",
    image: "/images/sp-cloudberry.png",
  },
  {
    slug: "blabar",
    name: "Blåbär",
    latin: "Vaccinium myrtillus",
    badge: "Bär",
    category: "vaxter",
    image: "/images/species-blueberry.png",
  },
  {
    slug: "havtorn",
    name: "Havtorn",
    latin: "Hippophae rhamnoides",
    badge: "Bär",
    category: "vaxter",
    image: "/images/sp-buckthorn.png",
  },
  {
    slug: "kantarell",
    name: "Kantarell",
    latin: "Cantharellus cibarius",
    badge: "Svamp",
    category: "svampar",
    image: "/images/species-chanterelle.png",
  },
  {
    slug: "karljohan",
    name: "Karljohan",
    latin: "Boletus edulis",
    badge: "Svamp",
    category: "svampar",
    image: "/images/sp-porcini.png",
  },
  {
    slug: "fjallig-blacksvamp",
    name: "Fjällig bläcksvamp",
    latin: "Coprinus comatus",
    badge: "Svamp",
    category: "svampar",
    image: "/images/svampar/Fjallig_Blacksvamp_Huvudbild_01.png",
  },
  {
    slug: "fjallig-taggsvamp",
    name: "Fjällig taggsvamp",
    latin: "Sarcodon imbricatus",
    badge: "Svamp",
    category: "svampar",
    image: "/images/svampar/Fjallig_Taggsvamp_Huvudbild_01.png",
  },
  {
    slug: "rod-flugsvamp",
    name: "Röd flugsvamp",
    latin: "Amanita muscaria",
    badge: "Svamp",
    category: "svampar",
    image: "/images/svampar/Rod_Flugsvamp_Huvudbild_01.png",
  },
  {
    slug: "fnoskticka",
    name: "Fnöskticka",
    latin: "Fomes fomentarius",
    badge: "Svamp",
    category: "svampar",
    image: "/images/svampar/Fnoskticka_Huvudbild_01.png",
  },
  {
    slug: "farticka",
    name: "Fårticka",
    latin: "Albatrellus ovinus",
    badge: "Svamp",
    category: "svampar",
    image: "/images/svampar/Farticka_Huvudbild_01.png",
  },
  {
    slug: "vartig-roksvamp",
    name: "Vårtig röksvamp",
    latin: "Lycoperdon perlatum",
    badge: "Svamp",
    category: "svampar",
    image: "/images/svampar/Vartig_Roksvamp_Huvudbild_01.png",
  },
  {
    slug: "tall",
    name: "Tall",
    latin: "Pinus sylvestris",
    badge: "Träd",
    category: "trad",
    image: "/images/species-pine.png",
  },
  {
    slug: "gran",
    name: "Gran",
    latin: "Picea abies",
    badge: "Träd",
    category: "trad",
    image: "/images/sp-spruce.png",
  },
  {
    slug: "ronn",
    name: "Rönn",
    latin: "Sorbus aucuparia",
    badge: "Träd",
    category: "trad",
    image: "/images/trad/Ronn_Huvudbild_01.png",
  },
  {
    slug: "salg",
    name: "Sälg",
    latin: "Salix caprea",
    badge: "Träd",
    category: "trad",
    image: "/images/trad/Salg_Huvudbild_01.png",
  },
  {
    slug: "graal",
    name: "Gråal",
    latin: "Alnus incana",
    badge: "Träd",
    category: "trad",
    image: "/images/trad/Graal_Huvudbild_01.png",
  },
  {
    slug: "bjork",
    name: "Björk",
    latin: "Betula pendula",
    badge: "Träd",
    category: "trad",
    image: "/images/trad/Bjork_Huvudbild_01.png",
  },
  {
    slug: "asp",
    name: "Asp",
    latin: "Populus tremula",
    badge: "Träd",
    category: "trad",
    image: "/images/trad/Asp_Huvudbild_01.png",
  },
]
